const words = [
  'God Jul',
  'Merry Christmas',
  'Sretan Božić',
  'Glædelig Jul',
  'Vrolijk Kerstfeest',
  'Feliz Natal',
  'Craciun Fericit',
  'Nadolig Llawen',
  'Boldog Karácsonyt',
  'Frohe Weihnachten',
  'Veselé Vánoce',
  'Feliz Navidad',
  'срећан Божић',
  'счастливого Рождества',
];
